theme: jekyll-theme-cayman

# hexo mathjax
math:
  engine: 'mathjax' # or 'katex'
  mathjax:
    src: "//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML"
    config:
      # MathJax config
